apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:

  opensky-id: "alessio1996a-api-client"
  opensky-secret: "d9EQGD7l0PdOCH1XyWQkHHbH1nAsKfOq"
  sender-email: "tornabenealessio@gmail.com"
  sender-password: "turlvzdywsbpifxc"