apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      labels:
        app: data-collector
        monitoring: "true"
    spec:
      containers:
      - name: data-collector
        image: dsbd-data-collector:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        - containerPort: 50052
        - containerPort: 8001
        env:
        # Downward API
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"

        # --- MODIFICA FONDAMENTALE ---
        # Questa variabile sovrascrive il default "localhost" nel tuo codice Python
        - name: MONGO_URL
          value: "mongodb://mongodb:27017/"
        # -----------------------------

        - name: USER_MANAGER_GRPC
          value: "user-manager-service:50051"
        - name: MONGODB_HOST
          value: "mongodb"
        - name: OPENSKY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: opensky-id
        - name: OPENSKY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: opensky-secret
---
apiVersion: v1
kind: Service
metadata:
  name: data-collector-service
spec:
  selector:
    app: data-collector
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001
    - name: grpc
      protocol: TCP
      port: 50052
      targetPort: 50052
    - name: metrics
      protocol: TCP
      port: 8001
      targetPort: 8001