apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
      - name: notifier
        image: dsbd-notifier:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
        env:
        # --- MODIFICHE FONDAMENTALI ---
        # 1. Forza Python a stampare subito i log (risolve il problema log vuoti)
        - name: PYTHONUNBUFFERED
          value: "1"

        # 2. Specifica il topic corretto (deve coincidere con quello dell'Alert System)
        - name: KAFKA_TOPIC
          value: "to-notifier"
        # ------------------------------

        # Downward API
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: SENDER_EMAIL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: sender-email
        - name: SENDER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: sender-password
---
apiVersion: v1
kind: Service
metadata:
  name: notifier-service
spec:
  selector:
    app: notifier
  ports:
    - name: metrics
      protocol: TCP
      port: 8002
      targetPort: 8002