#database Postgres
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: homework3
spec:
  serviceName: "user-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432

          # Variabili d'ambiente dai Secrets
          env:
            - name: POSTGRES_DB
              valueFrom: {secretKeyRef: {name: app-secrets, key: POSTGRES_DB}}
            - name: POSTGRES_USER
              valueFrom: {secretKeyRef: {name: app-secrets, key: POSTGRES_USER}}
            - name: POSTGRES_PASSWORD
              valueFrom: {secretKeyRef: {name: app-secrets, key: POSTGRES_PASSWORD}}

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: user-db-service
  namespace: homework3
spec:
  selector:
    app: user-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
#database mongo
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: homework3
spec:
  serviceName: "mongo-service"
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017

          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db

  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: homework3
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017