#Deployment dello user-manager
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manager
  namespace: homework3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-manager
  template:
    metadata:
      labels:
        app: user-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: user-manager
          image: user-manager:v1
          imagePullPolicy: Never

          ports:
            - containerPort: 50051 #gRPC
            - containerPort: 8000  #metriche per Prometheus
            - containerPort: 5000  #Flask

          env:
            #variabili del file di ambiente
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: POSTGRES_HOST
              value: "user-db-service.homework3.svc.cluster.local"
            - name: POSTGRES_USER
              valueFrom: {secretKeyRef: {name: app-secrets, key: POSTGRES_USER}}
            - name: POSTGRES_PASSWORD
              valueFrom: {secretKeyRef: {name: app-secrets, key: POSTGRES_PASSWORD}}
            - name: POSTGRES_DB
              valueFrom: {secretKeyRef: {name: app-secrets, key: POSTGRES_DB}}
            - name: MY_NODE_NAME
              valueFrom: {fieldRef: {fieldPath: spec.nodeName}}
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DB)"

---
apiVersion: v1
kind: Service
metadata:
  name: user-manager-service
  namespace: homework3
spec:
  selector:
    app: user-manager
  ports:
    - name: http
      port: 5000
      targetPort: 5000
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: metrics
      port: 8000
      targetPort: 8000

---

#deployment del data-collector
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collector
  namespace: homework3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      labels:
        app: data-collector
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
    spec:
      containers:
        - name: data-collector
          image: data-collector:v1
          imagePullPolicy: Never

          ports:
            - containerPort: 5001
            - containerPort: 50052
            - containerPort: 8001

          env:
            #variabili di ambiente
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service.homework3.svc.cluster.local:9092"
            - name: MONGO_URL
              value: "mongodb://mongo-service.homework3.svc.cluster.local:27017/"
            - name: USER_MANAGER_GRPC
              value: "user-manager-service.homework3.svc.cluster.local:50051"
            - name: OPENSKY_CLIENT_ID
              valueFrom: {secretKeyRef: {name: app-secrets, key: OPENSKY_CLIENT_ID}}
            - name: OPENSKY_CLIENT_SECRET
              valueFrom: {secretKeyRef: {name: app-secrets, key: OPENSKY_CLIENT_SECRET}}
            - name: MY_NODE_NAME
              valueFrom: {fieldRef: {fieldPath: spec.nodeName}}

---
apiVersion: v1
kind: Service
metadata:
  name: data-collector-service
  namespace: homework3
spec:
  selector:
    app: data-collector
  ports:
    - name: http
      port: 5001
      targetPort: 5001
    - name: grpc
      port: 50052
      targetPort: 50052
    - name: metrics
      port: 8001
      targetPort: 8001

---

#deployment del notifier
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  namespace: homework3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8002"
    spec:
      containers:
        - name: notifier
          image: notifier:v1
          imagePullPolicy: Never

          ports:
            - containerPort: 8002

          env:
            #variabili di ambiente
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service.homework3.svc.cluster.local:9092"
            - name: SENDER_EMAIL
              valueFrom: {secretKeyRef: {name: app-secrets, key: GMAIL_USER}}
            - name: SENDER_PASSWORD
              valueFrom: {secretKeyRef: {name: app-secrets, key: GMAIL_PASSWORD}}
            - name: MY_NODE_NAME
              valueFrom: {fieldRef: {fieldPath: spec.nodeName}}

---
apiVersion: v1
kind: Service
metadata:
  name: notifier-service
  namespace: homework3
spec:
  selector:
    app: notifier
  ports:
    - name: metrics
      port: 8002
      targetPort: 8002

---

#deploymente dell alert-system
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-system
  namespace: homework3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-system
  template:
    metadata:
      labels:
        app: alert-system
    spec:
      containers:
        - name: alert-system
          image: alert-system:v1
          imagePullPolicy: Never

          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service.homework3.svc.cluster.local:9092"
            - name: MONGO_URL
              value: "mongodb://mongo-service.homework3.svc.cluster.local:27017/"
            - name: MY_NODE_NAME
              valueFrom: {fieldRef: {fieldPath: spec.nodeName}}