apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: homework3
type: Opaque
stringData:
  #credenziali OpenSky
  OPENSKY_CLIENT_ID: "alessio1996a-api-client"
  OPENSKY_CLIENT_SECRET: "d9EQGD7l0PdOCH1XyWQkHHbH1nAsKfOq"

  #credenziali Gmail per il Notifier
  GMAIL_USER: "tornabenealessio@gmail.com"
  GMAIL_PASSWORD: "turlvzdywsbpifxc"

  #credenziali database Postgres
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "users_db"