server {
    listen 80;
    server_name localhost;

    location /users {

        proxy_pass http://user_manager_service:5000;
    }

    location /interests {
        proxy_pass http://data_collector_service:5001;
    }

    location /flights {
        proxy_pass http://data_collector_service:5001;
    }
}