server {
    listen 80;
    server_name localhost;

    location /users {
        # CORRETTO: usa i trattini come nel file YAML del servizio
        proxy_pass http://user-manager-service:5000;
    }

    location /interests {
        # CORRETTO: usa i trattini
        proxy_pass http://data-collector-service:5001;
    }

    location /flights {
        # CORRETTO: usa i trattini
        proxy_pass http://data-collector-service:5001;
    }
}